server:
  servlet:
    context-path: /imperial
  port: 8085

logging:
  level:
    root: INFO
    org:
      apache:
        coyote:
          http11:
            Http11InputBuffer: DEBUG
    com:
      rlm: DEBUG
spring:
  application:
    name: imperialcom
  profiles:
    active: standalone
  jackson:
    default-property-inclusion: NON_NULL